-- AlterTable: Add reminder tracking fields to Lead
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "aiScore" INTEGER;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "aiNotes" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "expiry90Sent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "expiry30Sent" BOOLEAN NOT NULL DEFAULT false;
